name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/deploy-edge-functions.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    name: Deploy Edge Functions to Supabase
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install Supabase CLI
        run: |
          npm install -g supabase@latest
          
      - name: Verify Supabase CLI installation
        run: |
          supabase --version
          
      - name: Authenticate with Supabase
        run: |
          echo "${{ secrets.SUPABASE_ACCESS_TOKEN }}" | supabase login --token
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          
      - name: Link to Supabase project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          
      - name: Deploy IngrediCheck function
        run: |
          echo "Deploying ingredicheck function..."
          supabase functions deploy ingredicheck --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          
      - name: Deploy Background function
        run: |
          echo "Deploying background function..."
          supabase functions deploy background --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          
      - name: Verify deployments
        run: |
          echo "Verifying function deployments..."
          supabase functions list --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          
      - name: Deployment Summary
        run: |
          echo "✅ Successfully deployed edge functions:"
          echo "  - ingredicheck"
          echo "  - background"
          echo ""
          echo "Functions are now live and ready to receive requests."
